<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\unl_user\Helper;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;

/**
 * Implements hook_install().
 */
function unl_user_install() {
  \Drupal::configFactory()->getEditable('user.settings')
    ->set('register', UserInterface::REGISTER_ADMINISTRATORS_ONLY)
    ->save(TRUE);
}

/**
 * Implements hook_user_format_name_alter().
 */
function unl_user_user_format_name_alter(&$name, AccountInterface $account) {
  $displayName = \Drupal::service('user.data')->get('unl_user', $account->id(), 'displayName');
  if ($displayName) {
    $name = $displayName;
  }
}

/**
 * Implements hook_user_login().
 */
function unl_user_user_login(AccountInterface $account) {
  $last_login = $account->getLastLoginTime();
  $created = $account->getCreatedTime();

  if (empty($last_login) || $last_login == 0 || $last_login == $created) {
    // First login by the user. Update the user data immediately to ensure correctness.
    $helper = new Helper();
    $user = User::load($account->id());
    $result = $helper->updateUserData($user);

    if ($result) {
      \Drupal::logger('unl_user')->info('UNL User data for ' . $user->getAccountName() . ' updated during first login');
    }
    else {
      \Drupal::logger('unl_user')->notice('UNL User data for ' . $user->getAccountName() . ' failed to update during first login.');
    }
  }
  else {
    // Schedule a user data update for the account. Can be done slightly lazily
    // during the termination event since this user already has data populated
    // that is likely still current.
    \Drupal::service('unl_user.update_user_terminate_subscriber')->queueUpdate($account);
  }
}
